# Generated by Django 5.1.15 on 2026-06-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="answers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="auto_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                    ("reading", "Reading"),
                    ("listening", "Listening"),
                    ("quiz", "Quiz"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                    ("reading", "Reading"),
                    ("listening", "Listening"),
                    ("quiz", "Quiz"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_options",
                "ordering": ["order", "id"],
            },
        ),
    ]
