# Generated by Django 5.1.15 on 2026-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_exercise_content_text_exercise_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="audio_recording_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
