# Generated by Django 5.1.15 on 2026-08-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sectionattempt_testformat_mocktesttemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PronunciationDrill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_text", models.CharField(max_length=255)),
                (
                    "contrast_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phoneme_hint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drill_type",
                    models.CharField(
                        choices=[
                            ("word", "Word"),
                            ("sentence", "Sentence"),
                            ("minimal_pair", "Minimal Pair"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pronunciation_drills_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_drills",
                        to="core.learningmodule",
                    ),
                ),
            ],
            options={
                "db_table": "pronunciation_drills",
                "ordering": ["difficulty_level", "id"],
            },
        ),
        migrations.CreateModel(
            name="RubricTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("reading", "Reading"),
                            ("listening", "Listening"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_default_for_type", models.BooleanField(default=False)),
                (
                    "scale_min",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "scale_max",
                    models.DecimalField(decimal_places=1, default=9, max_digits=5),
                ),
                (
                    "score_step",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            (
                                "mean_down_half",
                                "Mean, rounded DOWN to nearest 0.5 (IELTS convention)",
                            ),
                            ("mean_nearest_half", "Mean, rounded to nearest 0.5"),
                            ("mean", "Mean (2 decimal places)"),
                            ("sum", "Sum of criterion scores"),
                        ],
                        default="mean_down_half",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rubric_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rubric_templates",
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="core.rubrictemplate",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_criteria",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="rubric_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercises",
                to="core.rubrictemplate",
            ),
        ),
        migrations.CreateModel(
            name="WritingAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_offset", models.PositiveIntegerField()),
                ("end_offset", models.PositiveIntegerField()),
                ("quoted_text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grammar", "Grammar"),
                            ("vocabulary", "Vocabulary"),
                            ("spelling", "Spelling"),
                            ("coherence", "Coherence"),
                            ("task_response", "Task response"),
                            ("praise", "Praise"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("suggested_correction", models.TextField(blank=True, null=True)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotations_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "db_table": "writing_annotations",
                "ordering": ["start_offset", "end_offset", "id"],
            },
        ),
        migrations.CreateModel(
            name="PronunciationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="pronunciation/%Y/%m/")),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fluency_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "completeness_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "prosody_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("word_results", models.JSONField(blank=True, null=True)),
                ("engine", models.CharField(blank=True, default="", max_length=50)),
                ("engine_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.pronunciationdrill",
                    ),
                ),
            ],
            options={
                "db_table": "pronunciation_attempts",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["student", "drill", "-created_at"],
                        name="pronunciati_student_f8f9d4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RubricBandDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_value", models.DecimalField(decimal_places=1, max_digits=5)),
                ("label", models.CharField(blank=True, max_length=50)),
                ("descriptor", models.TextField()),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="band_descriptors",
                        to="core.rubriccriterion",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_band_descriptors",
                "ordering": ["band_value", "id"],
                "unique_together": {("criterion", "band_value")},
            },
        ),
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=1, max_digits=5)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="core.feedback",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="core.rubriccriterion",
                    ),
                ),
            ],
            options={
                "db_table": "criterion_scores",
                "unique_together": {("feedback", "criterion")},
            },
        ),
        migrations.AddConstraint(
            model_name="rubrictemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default_for_type", True)),
                fields=("exercise_type",),
                name="one_default_rubric_per_exercise_type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rubriccriterion",
            unique_together={("template", "code")},
        ),
        migrations.AddConstraint(
            model_name="writingannotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset__gt", models.F("start_offset"))),
                name="writing_annotation_nonempty_range",
            ),
        ),
    ]
