# Generated by Django 5.1.15 on 2026-08-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pronunciationdrill_rubrictemplate_rubriccriterion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mocktesttemplate",
            name="is_published",
        ),
    ]
