# Generated by Django 5.1.15 on 2026-08-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_mocktesttemplate_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_words",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsection",
            name="item_flow",
            field=models.CharField(
                choices=[
                    ("free", "All parts available at once"),
                    ("sequential", "One part at a time, no going back"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testsectionexercise",
            name="max_record_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsectionexercise",
            name="prep_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsectionexercise",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="testformat",
            name="overall_strategy",
            field=models.CharField(
                choices=[
                    ("band_average", "Band average"),
                    ("scaled_sum", "Scaled sum"),
                    ("mean_percent", "Mean percent"),
                ],
                max_length=20,
            ),
        ),
    ]
