# Generated by Django 5.1.15 on 2026-08-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_question_max_words_testsection_item_flow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="mode",
            field=models.CharField(
                choices=[("exam", "Exam order"), ("practice", "Any order")],
                default="exam",
                max_length=20,
            ),
        ),
    ]
