# Generated by Django 5.1.15 on 2026-09-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_testattempt_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mistake_explanation", "Mistake explanation"),
                            ("feedback_review", "Feedback review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField()),
                ("engine", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_insights_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "db_table": "ai_insights",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["submission", "kind", "-created_at"],
                        name="ai_insights_submiss_c4f623_idx",
                    )
                ],
            },
        ),
    ]
