# Generated by Django 5.1.15 on 2026-08-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("band_4_5", "Band 4–5"),
                    ("band_5_6", "Band 5–6"),
                    ("band_6_7", "Band 6–7"),
                    ("band_7_8", "Band 7–8"),
                    ("band_8_9", "Band 8–9"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("life", "Life"),
                    ("sports", "Sports"),
                    ("education", "Education"),
                    ("work", "Work"),
                    ("travel", "Travel"),
                    ("environment", "Environment"),
                    ("technology", "Technology"),
                    ("health", "Health"),
                    ("culture", "Culture"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learningmodule",
            name="band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("band_4_5", "Band 4–5"),
                    ("band_5_6", "Band 5–6"),
                    ("band_6_7", "Band 6–7"),
                    ("band_7_8", "Band 7–8"),
                    ("band_8_9", "Band 8–9"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learningmodule",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("life", "Life"),
                    ("sports", "Sports"),
                    ("education", "Education"),
                    ("work", "Work"),
                    ("travel", "Travel"),
                    ("environment", "Environment"),
                    ("technology", "Technology"),
                    ("health", "Health"),
                    ("culture", "Culture"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
