# Generated by Django 5.1.15 on 2026-08-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_exercise_band_exercise_topic_learningmodule_band_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("ended", "Ended"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
