# Generated by Django 5.1.15 on 2026-09-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_meeting_scheduled_at_meeting_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionattempt",
            name="ai_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sectionattempt",
            name="ai_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectionattempt",
            name="ai_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectionattempt",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
